### ISSUE TITLE
Shin Megami Tensei Devil Survivor Overclocked (USA)

### ISSUE THREAD

**Issue by ghost** [Panda3DS-emu/Panda3DS-Games-List#109]
### Game Name (and version if necessary)

Shin Megami Tensei Devil Survivor Overclocked

### Operating System

Windows 11 23H2

### Game State

Playable without Audio

**Comment by notprogramminggames** [comment]
How is it playable for you? Screenshots? Isn't audio unimplemented?
Also i've already tested the NTSC-U version so you just need to put the form in a comment under mine.

**Comment by ghost** [comment]
no it s unimplemented and without audio

**Comment by ghost** [comment]
yes i've changed it

**Comment by ghost** [comment]
and without audio

**Comment by ghost** [comment]
no its not

**Comment by ghost** [comment]
optional

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
if i mean to you [notprogramminggames] for not implementing audio to panda3ds

**Comment by ghost** [comment]
what you will guess to you and me

**Comment by wheremyfoodat** [comment]
> How is it playable for you? Screenshots? Isn't audio unimplemented? Also i've already tested the NTSC-U version so you just need to put the form in a comment under mine.

You can get audio by tweaking config but only if you use the LLE DSP interpreter which is slow and not recommended

**Comment by Adamillo** [comment]
Please don't type like this. This isn't a chatting platform like Discord. You gotta post a single text on a platform like Github

**Comment by ghost** [comment]
![image_2024-03-08_173203032](https://github.com/Panda3DS-emu/Panda3DS-Games-List/assets/158190026/93cffbc5-abd5-4bb7-99af-1217b5ad4e95)

**Comment by ghost** [comment]
how do i config panda3ds

**Comment by notprogramminggames** [comment]
> ![image_2024-03-08_173203032](https://private-user-images.githubusercontent.com/158190026/311359424-93cffbc5-abd5-4bb7-99af-1217b5ad4e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Mzc1NDEsIm5iZiI6MTcwOTkzNzI0MSwicGF0aCI6Ii8xNTgxOTAwMjYvMzExMzU5NDI0LTkzY2ZmYmM1LWFiZDUtNGJiNy05OWFmLTEyMTdiNWFkNGU5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQyMjM0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTZjZDEyMDYzYmVmMzlhMDRlYTJjNzVmY2E3ZTVjN2ExMDFmOTFkZTZhMDBkZmQxN2JjMzNiNTY0NjU1MWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uayCyOXqU6YGfMBzQYl7_2-21qInJl8GxsCWTtN7V10)

Thats interesting, what build are you using?

**Comment by ghost** [comment]
qt build

**Comment by ghost** [comment]
not the windows build

**Comment by notprogramminggames** [comment]
Shouldn't this be closed and moved over to #107 ?

**Comment by ghost** [comment]
yes
