### ISSUE TITLE
Devil Survivor Over Clock (Japan)

### ISSUE THREAD

**Issue by ghost** [Panda3DS-emu/Panda3DS-Games-List#110]
### Game Name (and version if necessary)

Devil Survivor Over Clock

### Operating System

Windows 11 23H2

### Game State

Playable without Audio

**Comment by ghost** [comment]
i mean

**Comment by KostaSaizo7** [comment]
Duplicate of https://github.com/Panda3DS-emu/Panda3DS-Games-List/issues/107
