### ISSUE TITLE
Shin Megami Tensei IV (Japan)

### ISSUE THREAD

**Issue by ghost** [Panda3DS-emu/Panda3DS-Games-List#147]
### Game Name (and version if necessary)

Shin Megami Tensei IV (Japan)

### Operating System

Windows 11

### Game State

status-perfect

### Screenshots

No Screenshots

**Comment by KostaSaizo7** [comment]
I don't think we need different issues for different regions of the same game, so let's just keep https://github.com/Panda3DS-emu/Panda3DS-Games-List/issues/146
