### ISSUE TITLE
Detective Pikachu

### ISSUE THREAD

**Issue by SuperTavor** [Panda3DS-emu/Panda3DS-Games-List#88]
### Game Name (and version if necessary)

Detective Pikachu

### Hardware Specs (If necessary)

CPU: 13th Gen Intel(R) Core(TM) i7-13700F   2.10 GHz
GPU: NVIDIA RTX 3060

### Operating System

Windows 11

### Game State

Won't start.
Error:
[FATAL] Failed to find paddr

**Comment by KostaSaizo7** [comment]
Duplicate of #24
