### ISSUE TITLE
Pokemon X

### ISSUE THREAD

**Issue by Ishan09811** [Panda3DS-emu/Panda3DS-Games-List#90]
### Game Name (and version if necessary)

Pokemon X

### Hardware Specs (If necessary)

CPU : Mediatek Dimensity 810
GPU : MALI

### Operating System

Android 12

### Game State

Black screen (Status: boots nothing)

### Screenshots

![Screenshot_20240125-123948](https://github.com/Panda3DS-emu/Panda3DS-Games-List/assets/156402647/88322208-fe6e-418d-81fa-b2fca632c807)

**Comment by wheremyfoodat** [comment]
Please use the PC version for submitting anything to this repo. Report is wrong and also a duplicate.

![image](https://github.com/Panda3DS-emu/Panda3DS-Games-List/assets/44909372/5733d75b-689b-4502-819e-2bd9eb5fae16)
![image](https://github.com/Panda3DS-emu/Panda3DS-Games-List/assets/44909372/4d2b53b7-9e53-42a2-a582-f365cb8d3a96)

**Comment by Ishan09811** [comment]
ok
